//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_pay
    {
        public int Pay_Id { get; set; }
        public Nullable<int> Purchase_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
    
        public virtual purchase purchase { get; set; }
    }
}
