//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.purchase_pay = new HashSet<purchase_pay>();
        }
    
        public int Purchase_Id { get; set; }
        public string Purchase_Name { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Pay_Id { get; set; }
    
        public virtual category category { get; set; }
        public virtual company company { get; set; }
        public virtual pay pay { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_pay> purchase_pay { get; set; }
    }
}
