//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int Salary_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<decimal> Salary_Amount { get; set; }
        public Nullable<decimal> Advance_Cut { get; set; }
        public Nullable<decimal> Total_Pay { get; set; }
        public Nullable<System.DateTime> Salary_Date { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
