//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int Stock_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual category category { get; set; }
        public virtual company company { get; set; }
        public virtual product product { get; set; }
    }
}
